options:
  hide_event_toc: False
  hide_mlh_toc: False
  min_resume_age: 17
custom_fields:
 - name: ethnicity
   label: "What is your race/ethnicity?"
   type: select
   options:
    - American Indian or Alaskan Native
    - Asian / Pacific Islander
    - Black or African American
    - Hispanic
    - White / Caucasian
    - Multiple ethnicity / Other
    - Prefer not to answer
 - name: minor
   label: "Minor (if applicable)"
 - name: graduation_year
   label: "What is your graduation year?"
   validate_regex: '\d{4}'
   validate_error: "Your graduation year is not valid (e.g. 2020)"
 - name: dietary_preferences
   label: "What are your dietary preferences?"
   type: multiselect
   options:
    - Vegan
    - Vegetarian
    - Non-Vegetarian
    - Vegetarian (No Egg)
    - Kosher
    - Halal
    - Other (please specify in food allergies question)  
- name: food_allergies
   label: "What are your food allergies, if any?"
- name: linkedin_url
   label: 'LinkedIn URL'
   validate_regex: '\A(https:\/\/)?(www.)?linkedin.com\/in\/\S+\z'
   validate_error: 'Your Linkedin URL is invalid. Example format: https://linkedin.com/in/yourprofile'
 - name: github_url
   label: 'GitHub URL'
   validate_regex: '\A(https:\/\/)?(www.)?github.com\/\S+\z'
   validate_error: 'Your Github URL is invalid. Example format: https://github.com/yourprofile'
 - name: other_url
   label: 'Personal Website or Portfolio URL'
 - name: been_to_hackathon
   label: 'Have you been to a hackathon before?'
   type: boolean
   required: True
   toggle_field: how_many_hackathons
 - name: how_many_hackathons
   label: "How many hackathons have you previously attended?"
   type: select
   options:
    - 1
    - 2
    - 3
    - 4
    - 5 or more
   hidden: True
 - name: been_to_hackher
   label: 'Have you previously attended Hack(H)er413??'
   type: boolean
   required: True
   toggle_field: previous_hackher_comments
 - name: previous_hackher_comments
   label: "Since you have previously attended Hack(H)er413 before, what's one thing you would like to see different or new this year?"
   type: textarea
   max_chars: 500
   hidden: True
 - name: programming_skills
   label: "Programming Skills (select all that apply)"
   type: multiselect
   options:
    - HTML/CSS
    - Javascript
    - Node.js
    - Express
    - Angular
    - React
    - Vue
    - PHP
    - SQL
    - Ruby/Ruby on Rails
    - Java
    - Kotlin
    - Swift
    - Objective C
    - C/C++/C#
    - Python
 - name: hardware_skills
   label: 'Hardware Skills (select all that apply)'
   type: multiselect
   options:
    - Embedded Systems
    - Robotics
    - Wireless Communications
    - Circuits
    - 3D Printing
 - name: hardware_preferences
   label: 'If you are interested in hardware, what hardware do you want to see at Hack(H)er413?'
   type: textarea
   max_chars: 500
 - name: other_skills
   label: 'If there are any other tech or non-tech related skills not listed above that you would like to share, list them below'
   type: textarea
   max_chars: 500
 - name: any_hack
   label: 'If you could create any hack at Hack(H)er413, without any technical, financial, or time restrictions, what would it be?'
   type: textarea
   max_chars: 500
 - name: empower
   label: 'How do you empower diversity in technology or how do you plan to empower diversity in technology in the future?'
   type: textarea
   max_chars: 500
 - name: how_did_you_hear
   label: 'How did you learn about Hack(H)er413? '
   type: textarea
   max_chars: 500
 - name: sleeping
   label: 'Do you plan on sleeping during the hackathon? This helps us to get a headcount for sleeping accommodations!'
   type: boolean
 - name: beginner
   label: "Please select the attendee track you identify with and will be participating in at the hackathon. Our tracks are simply two categories we utilize to organize events at the hackathon so participants can have an understanding of the difficulty/programming level before attending. Any participant can attend any event under any track, this is simply a way for us to organize the various events under two identifiers! The two tracks at Hack(H)er413 2020 are: "
   type: select
   options:
    - Beginner Track (recommended for undergraduate students and first-time programmers, includes introductory workshops given by sponsor companies and meet-ups for beginners in tech)
    - Beginner++ Track (recommended for intermediate programmers, Masters and Ph.D. students; includes tech talks given by computer science & technology professors on their research/dissertations and more) 
 - name: fun_question
   label: "Are you excited to become a part of the beehive?! #iBeelong #PartoftheSwarm"
   type: select
   options:
    - Yes
    - YES
    - HELL YES
